name: GitVersion Tag

permissions:
  id-token: write
  contents: write

on:
  push: 
    branches: ["dev/master", "master"]

jobs:
  calculate-version:
    name:  Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - name: Calculate Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
    - name: Tag repo
      run: |
        echo ${{ steps.gitversion.outputs.semVer }}
        git tag ${{ steps.gitversion.outputs.semVer }}
        git push origin ${{ steps.gitversion.outputs.semVer }}
    - name: Call .NET Build Workflow
      uses: TheCodeKeep/ghActions-tester./github/workflows@main
      with:
        buildVersion: ${{ steps.gitversion.outputs.semVer }}