name: GitVersion Tag

permissions:
  id-token: write
  contents: write

on:
  pull_request:
    branches: ["master", "dev/master"]
    types:
      - closed

jobs:
  calculate-version:
    name:  Calculate Version
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - name: Calculate Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
  - name: Tag repo
    run: |
      echo ${{ steps.gitversion.outputs.semVer }}
      git tag v${{ steps.gitversion.outputs.semVer }}
      git push origin $${{ steps.gitversion.outputs.semVer }}